server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: shop-backed-api
          uri: lb://SHOP-BACKEND-API
          predicates:
            - Path=/api/v1/**
          - id: shop-picture-service-api
          uri: lb://SHOP-PICTURE-SERVICE-API
          predicates:
            - Path=/api/v1/**
        - id: shop-admin
          uri: lb://SHOP-ADMIN
          predicates:
            - Path=/admin/**
